name: Docker CI/CD for ECR

on:
  push:
    branches:
      - main
      - master  # Runs on push to main or master
  pull_request:
    branches:
      - main
      - master  # Runs on pull requests to main or master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        run: |
          docker build -t demo-service . || exit 1
          

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Tag and Push to ECR
        run: |
          docker tag demo-service:latest ${{ secrets.ECR_REPOSITORY }}:latest || exit 1
          docker push ${{ secrets.ECR_REPOSITORY }}:latest || exit 1