name: Docker CI

on:
  push:
    branches:
      - main
      - master  # Runs on push to main or master
  pull_request:
    branches:
      - main
      - master  # Runs on pull requests to main or master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        run: |
          docker build -t my-spring-app .